//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _86ME_ver2.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_86ME_ver2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap add2 {
            get {
                object obj = ResourceManager.GetObject("add2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap addmotion {
            get {
                object obj = ResourceManager.GetObject("addmotion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap default_BG {
            get {
                object obj = ResourceManager.GetObject("default_BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap delmotion {
            get {
                object obj = ResourceManager.GetObject("delmotion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap down_arrow {
            get {
                object obj = ResourceManager.GetObject("down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap downmotion {
            get {
                object obj = ResourceManager.GetObject("downmotion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 #include &lt;FirmataPlus86.h&gt;
        ///
        ///#define CONNECT_86DUINO_METHOD 0 // 0: USB Serial 1: BlueTooth 2: Arduino WiFi Shield 3: Ethernet 4: ESP8266 WiFi 5: ESP8266 AP
        ///
        ///char* projectName = &quot;Hello, 86Duino&quot;;
        ///char* _ssid = &quot;your SSID&quot;;
        ///char* _password = &quot;your password&quot;; // If it is ESP8266 AP mode, the password can not be shorter that 8 chars.
        ///#define BT_ESP8266_Serial         Serial1
        ///#define BT_ESP8266_Serial_Baud    9600
        ///
        ///#if CONNECT_86DUINO_METHOD == 2 // Arduino WiFi Shield
        ///    bool _wep = false;
        ///    IPAddress _ip(0, [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string FirmataPlusAll {
            get {
                return ResourceManager.GetString("FirmataPlusAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] hand_close {
            get {
                object obj = ResourceManager.GetObject("hand_close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] hand_open {
            get {
                object obj = ResourceManager.GetObject("hand_open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap load_frame {
            get {
                object obj = ResourceManager.GetObject("load_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap modify {
            get {
                object obj = ResourceManager.GetObject("modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap off {
            get {
                object obj = ResourceManager.GetObject("off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap on {
            get {
                object obj = ResourceManager.GetObject("on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap p {
            get {
                object obj = ResourceManager.GetObject("p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap s {
            get {
                object obj = ResourceManager.GetObject("s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 #!/usr/bin/env python
        ///
        ///# -*- coding: utf-8 -*-
        ///
        ///&quot;&quot;&quot;
        ///Created on Wed Nov  25 13:17:15 2013
        ///
        ///@author: Alan Yorinks
        ///Copyright (c) 2013-14 Alan Yorinks All right reserved.
        ///
        ///This program is free software; you can redistribute it and/or
        ///modify it under the terms of the GNU Lesser General Public
        ///License as published by the Free Software Foundation; either
        ///version 2.1 of the License, or (at your option) any later version.
        ///
        ///This library is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; with [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string s2a_fm {
            get {
                return ResourceManager.GetString("s2a_fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap save_frame {
            get {
                object obj = ResourceManager.GetObject("save_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] sb2 {
            get {
                object obj = ResourceManager.GetObject("sb2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///	&quot;objName&quot;: &quot;Stage&quot;,
        ///	&quot;sounds&quot;: [{
        ///			&quot;soundName&quot;: &quot;pop&quot;,
        ///			&quot;soundID&quot;: 0,
        ///			&quot;md5&quot;: &quot;83a9787d4cb6f3b7632b4ddfebf74367.wav&quot;,
        ///			&quot;sampleCount&quot;: 258,
        ///			&quot;rate&quot;: 11025,
        ///			&quot;format&quot;: &quot;&quot;
        ///		}],
        ///	&quot;costumes&quot;: [{
        ///			&quot;costumeName&quot;: &quot;86scratch_background&quot;,
        ///			&quot;baseLayerID&quot;: 3,
        ///			&quot;baseLayerMD5&quot;: &quot;a8311e13b06e88aeb30d9bca77968fd5.png&quot;,
        ///			&quot;bitmapResolution&quot;: 2,
        ///			&quot;rotationCenterX&quot;: 480,
        ///			&quot;rotationCenterY&quot;: 360
        ///		}],
        ///	&quot;currentCostumeIndex&quot;: 0,
        ///	&quot;penLayerMD5&quot;: &quot;5c81a336fab8be57adc039a8a2b33ca9.png&quot;,
        ///	&quot;penLayerID&quot;: 0 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string sb2ProjectJson {
            get {
                return ResourceManager.GetString("sb2ProjectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 # -*- coding: utf-8 -*-
        ///
        ///&quot;&quot;&quot;
        ///Created on Wed Nov  25 13:17:15 2013
        ///
        ///@author: Alan Yorinks
        ///Copyright (c) 2013-14 Alan Yorinks All right reserved.
        ///
        ///@co-author: Sjoerd Dirk Meijer, fromScratchEd.nl (language support)
        ///
        ///This program is free software; you can redistribute it and/or
        ///modify it under the terms of the GNU Lesser General Public
        ///License as published by the Free Software Foundation; either
        ///version 2.1 of the License, or (at your option) any later version.
        ///
        ///This library is distributed in the hope that it  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string scratch_command_handlers {
            get {
                return ResourceManager.GetString("scratch_command_handlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 # -*- coding: utf-8 -*-
        ///&quot;&quot;&quot;
        ///Created on Mon Nov 25 14:45:49 2013
        ///
        ///@author: Alan Yorinks
        ///Copyright (c) 2013-14 Alan Yorinks All right reserved.
        ///
        ///This program is free software; you can redistribute it and/or
        ///modify it under the terms of the GNU Lesser General Public
        ///License as published by the Free Software Foundation; either
        ///version 2.1 of the License, or (at your option) any later version.
        ///
        ///This library is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warr [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string scratch_http_server {
            get {
                return ResourceManager.GetString("scratch_http_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap up_arrow {
            get {
                object obj = ResourceManager.GetObject("up_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap upmotion {
            get {
                object obj = ResourceManager.GetObject("upmotion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
